// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Velin-Todorov/zetta-task/internal/db"
	"github.com/Velin-Todorov/zetta-task/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewBookRepository creates a new instance of BookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookRepository {
	mock := &BookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BookRepository is an autogenerated mock type for the BookRepository type
type BookRepository struct {
	mock.Mock
}

type BookRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BookRepository) EXPECT() *BookRepository_Expecter {
	return &BookRepository_Expecter{mock: &_m.Mock}
}

// CreateBook provides a mock function for the type BookRepository
func (_mock *BookRepository) CreateBook(ctx context.Context, params db.CreateBookParams) (*db.Book, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateBook")
	}

	var r0 *db.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateBookParams) (*db.Book, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateBookParams) *db.Book); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateBookParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BookRepository_CreateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBook'
type BookRepository_CreateBook_Call struct {
	*mock.Call
}

// CreateBook is a helper method to define mock.On call
//   - ctx context.Context
//   - params db.CreateBookParams
func (_e *BookRepository_Expecter) CreateBook(ctx interface{}, params interface{}) *BookRepository_CreateBook_Call {
	return &BookRepository_CreateBook_Call{Call: _e.mock.On("CreateBook", ctx, params)}
}

func (_c *BookRepository_CreateBook_Call) Run(run func(ctx context.Context, params db.CreateBookParams)) *BookRepository_CreateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateBookParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateBookParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BookRepository_CreateBook_Call) Return(book *db.Book, err error) *BookRepository_CreateBook_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *BookRepository_CreateBook_Call) RunAndReturn(run func(ctx context.Context, params db.CreateBookParams) (*db.Book, error)) *BookRepository_CreateBook_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBook provides a mock function for the type BookRepository
func (_mock *BookRepository) DeleteBook(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BookRepository_DeleteBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBook'
type BookRepository_DeleteBook_Call struct {
	*mock.Call
}

// DeleteBook is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *BookRepository_Expecter) DeleteBook(ctx interface{}, id interface{}) *BookRepository_DeleteBook_Call {
	return &BookRepository_DeleteBook_Call{Call: _e.mock.On("DeleteBook", ctx, id)}
}

func (_c *BookRepository_DeleteBook_Call) Run(run func(ctx context.Context, id int64)) *BookRepository_DeleteBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BookRepository_DeleteBook_Call) Return(err error) *BookRepository_DeleteBook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BookRepository_DeleteBook_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *BookRepository_DeleteBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetBook provides a mock function for the type BookRepository
func (_mock *BookRepository) GetBook(ctx context.Context, id int64) (*db.Book, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBook")
	}

	var r0 *db.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*db.Book, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *db.Book); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BookRepository_GetBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBook'
type BookRepository_GetBook_Call struct {
	*mock.Call
}

// GetBook is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *BookRepository_Expecter) GetBook(ctx interface{}, id interface{}) *BookRepository_GetBook_Call {
	return &BookRepository_GetBook_Call{Call: _e.mock.On("GetBook", ctx, id)}
}

func (_c *BookRepository_GetBook_Call) Run(run func(ctx context.Context, id int64)) *BookRepository_GetBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BookRepository_GetBook_Call) Return(book *db.Book, err error) *BookRepository_GetBook_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *BookRepository_GetBook_Call) RunAndReturn(run func(ctx context.Context, id int64) (*db.Book, error)) *BookRepository_GetBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooks provides a mock function for the type BookRepository
func (_mock *BookRepository) GetBooks(ctx context.Context, filter repository.BookFilter) ([]db.Book, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetBooks")
	}

	var r0 []db.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.BookFilter) ([]db.Book, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.BookFilter) []db.Book); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.BookFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BookRepository_GetBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooks'
type BookRepository_GetBooks_Call struct {
	*mock.Call
}

// GetBooks is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.BookFilter
func (_e *BookRepository_Expecter) GetBooks(ctx interface{}, filter interface{}) *BookRepository_GetBooks_Call {
	return &BookRepository_GetBooks_Call{Call: _e.mock.On("GetBooks", ctx, filter)}
}

func (_c *BookRepository_GetBooks_Call) Run(run func(ctx context.Context, filter repository.BookFilter)) *BookRepository_GetBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.BookFilter
		if args[1] != nil {
			arg1 = args[1].(repository.BookFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BookRepository_GetBooks_Call) Return(books []db.Book, err error) *BookRepository_GetBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *BookRepository_GetBooks_Call) RunAndReturn(run func(ctx context.Context, filter repository.BookFilter) ([]db.Book, error)) *BookRepository_GetBooks_Call {
	_c.Call.Return(run)
	return _c
}

// SetBookCover provides a mock function for the type BookRepository
func (_mock *BookRepository) SetBookCover(ctx context.Context, params db.UpdateBookCoverParams) (*db.Book, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SetBookCover")
	}

	var r0 *db.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateBookCoverParams) (*db.Book, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateBookCoverParams) *db.Book); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.UpdateBookCoverParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BookRepository_SetBookCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBookCover'
type BookRepository_SetBookCover_Call struct {
	*mock.Call
}

// SetBookCover is a helper method to define mock.On call
//   - ctx context.Context
//   - params db.UpdateBookCoverParams
func (_e *BookRepository_Expecter) SetBookCover(ctx interface{}, params interface{}) *BookRepository_SetBookCover_Call {
	return &BookRepository_SetBookCover_Call{Call: _e.mock.On("SetBookCover", ctx, params)}
}

func (_c *BookRepository_SetBookCover_Call) Run(run func(ctx context.Context, params db.UpdateBookCoverParams)) *BookRepository_SetBookCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.UpdateBookCoverParams
		if args[1] != nil {
			arg1 = args[1].(db.UpdateBookCoverParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BookRepository_SetBookCover_Call) Return(book *db.Book, err error) *BookRepository_SetBookCover_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *BookRepository_SetBookCover_Call) RunAndReturn(run func(ctx context.Context, params db.UpdateBookCoverParams) (*db.Book, error)) *BookRepository_SetBookCover_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBook provides a mock function for the type BookRepository
func (_mock *BookRepository) UpdateBook(ctx context.Context, params db.UpdateBookParams) (*db.Book, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 *db.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateBookParams) (*db.Book, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateBookParams) *db.Book); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.UpdateBookParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BookRepository_UpdateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBook'
type BookRepository_UpdateBook_Call struct {
	*mock.Call
}

// UpdateBook is a helper method to define mock.On call
//   - ctx context.Context
//   - params db.UpdateBookParams
func (_e *BookRepository_Expecter) UpdateBook(ctx interface{}, params interface{}) *BookRepository_UpdateBook_Call {
	return &BookRepository_UpdateBook_Call{Call: _e.mock.On("UpdateBook", ctx, params)}
}

func (_c *BookRepository_UpdateBook_Call) Run(run func(ctx context.Context, params db.UpdateBookParams)) *BookRepository_UpdateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.UpdateBookParams
		if args[1] != nil {
			arg1 = args[1].(db.UpdateBookParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BookRepository_UpdateBook_Call) Return(book *db.Book, err error) *BookRepository_UpdateBook_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *BookRepository_UpdateBook_Call) RunAndReturn(run func(ctx context.Context, params db.UpdateBookParams) (*db.Book, error)) *BookRepository_UpdateBook_Call {
	_c.Call.Return(run)
	return _c
}
