// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewImageStore creates a new instance of ImageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageStore {
	mock := &ImageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ImageStore is an autogenerated mock type for the ImageStore type
type ImageStore struct {
	mock.Mock
}

type ImageStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ImageStore) EXPECT() *ImageStore_Expecter {
	return &ImageStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type ImageStore
func (_mock *ImageStore) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ImageStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ImageStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *ImageStore_Expecter) Delete(ctx interface{}, id interface{}) *ImageStore_Delete_Call {
	return &ImageStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ImageStore_Delete_Call) Run(run func(ctx context.Context, id int64)) *ImageStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ImageStore_Delete_Call) Return(err error) *ImageStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ImageStore_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *ImageStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type ImageStore
func (_mock *ImageStore) Save(ctx context.Context, id int64, r io.Reader) (string, error) {
	ret := _mock.Called(ctx, id, r)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, io.Reader) (string, error)); ok {
		return returnFunc(ctx, id, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, io.Reader) string); ok {
		r0 = returnFunc(ctx, id, r)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, id, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ImageStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type ImageStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - r io.Reader
func (_e *ImageStore_Expecter) Save(ctx interface{}, id interface{}, r interface{}) *ImageStore_Save_Call {
	return &ImageStore_Save_Call{Call: _e.mock.On("Save", ctx, id, r)}
}

func (_c *ImageStore_Save_Call) Run(run func(ctx context.Context, id int64, r io.Reader)) *ImageStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ImageStore_Save_Call) Return(s string, err error) *ImageStore_Save_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *ImageStore_Save_Call) RunAndReturn(run func(ctx context.Context, id int64, r io.Reader) (string, error)) *ImageStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
