// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: book.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createBook = `-- name: CreateBook :execresult
INSERT INTO ` + "`" + `books` + "`" + ` (title, author, published_at)
VALUES (?, ?, ?)
`

type CreateBookParams struct {
	Title       string
	Author      string
	PublishedAt time.Time
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBook, arg.Title, arg.Author, arg.PublishedAt)
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM ` + "`" + `books` + "`" + ` WHERE id = ?
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, title, author, cover_path, published_at FROM ` + "`" + `books` + "`" + ` WHERE id = ?
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.CoverPath,
		&i.PublishedAt,
	)
	return i, err
}

const updateBook = `-- name: UpdateBook :execresult
UPDATE ` + "`" + `books` + "`" + `
SET title = ?, author = ?, published_at = ?
WHERE id = ?
`

type UpdateBookParams struct {
	Title       string
	Author      string
	PublishedAt time.Time
	ID          int64
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBook,
		arg.Title,
		arg.Author,
		arg.PublishedAt,
		arg.ID,
	)
}

const updateBookCover = `-- name: UpdateBookCover :execresult
UPDATE ` + "`" + `books` + "`" + ` SET cover_path = ? WHERE id = ?
`

type UpdateBookCoverParams struct {
	CoverPath sql.NullString
	ID        int64
}

func (q *Queries) UpdateBookCover(ctx context.Context, arg UpdateBookCoverParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBookCover, arg.CoverPath, arg.ID)
}
